* research-hackage

[[https://hackage.haskell.org/package/chart-hackage][file:https://img.shields.io/hackage/v/research-hackage.svg]] [[https://github.com/tonyday567/chart-hackage/actions?query=workflow%3Ahaskell-ci][file:https://github.com/tonyday567/research-hackage/workflows/haskell-ci/badge.svg]]

This repo is an experiment in:

- reading Haskell package information from =~/.cabal/packages/hackage.haskell.org/01-index.tar"=
- parsing cabal details using [[https://hackage.haskell.org/package/flatparse-0.2.2.0][flatparse]] and [[https://hackage.haskell.org/package/streamly][streamly]].
- creating dependency charts and graphing them with graphviz via [[https://github.com/tonyday567/dotparse][dotparse]] and [[https://hackage.haskell.org/package/chart-svg][chart-svg]].
- using org-mode for rapid Haskell development.

* code

** setup & development process

Notes on how to run ghci within org-mode are available at [[https://github.com/tonyday567/checklist#babel][checklist: How I start Haskell.]]

#+begin_src haskell
:set -XOverloadedStrings
:set -Wno-type-defaults
:set prompt "> "
putStrLn "ok"
#+end_src

#+RESULTS:
: *Research.Hackage> *Research.Hackage> *Research.Hackage> > ok

#+begin_src haskell
:r
import qualified Streamly.Prelude as S
import qualified Streamly.Internal.Data.Unfold as Unfold
import Data.Function
import Streamly.External.Archive
import Data.Either
import qualified Data.ByteString.Char8 as C
import Data.Bifunctor
import qualified Data.Map.Strict as Map
import DotParse
import Algebra.Graph
import qualified Algebra.Graph.ToGraph as ToGraph
import Data.Foldable
import Chart hiding (pathParse)
import Optics.Core
putStrLn "ok"
#+end_src

#+RESULTS:
: ok

The development loop largely starts with re-establishment of state by running the code below, which represents milestones in parsing cabal index data, and (eventual) reification in ~Research.Hackage~.

#+begin_src haskell :results output
vlibs <- Map.delete "acme-everything" <$> validLatestLibs
deps = fmap (fromRight undefined . parseDeps . mconcat . mconcat . rawBuildDeps . snd) vlibs
bdnames <- fmap (fmap fst) $ fmap Map.toList $ S.fold count $ S.concatMap S.fromList $ S.fromList $ fmap snd $ Map.toList deps
depsExclude = filter (not . (`elem` (Map.keys vlibs))) bdnames
vdeps = Map.filter (not . null) $ fmap (filter (not . (`elem` depsExclude))) deps
depG = stars (Map.toList vdeps)
#+end_src

#+RESULTS:

#+begin_src haskell :results output :exports both
vertexCount depG
edgeCount depG
#+end_src

#+RESULTS:
: 14624
: 105693

depG is an algebraic-graph of the latest cabal library package names as the vertexes and their dependencies as the edges.

** archive

archive is located at =~/.cabal/packages/hackage.haskell.org/01-index.tar= and contains @ 290k unique entries (May 2022).

All pathNames exist, all file types are regular and there are no utf8 issues with pathNames
so we use the header pathName to roll up the archive

package count:

#+begin_src haskell :results output :exports both
:t groupByPathName
:t Unfold.take 10000000 archive
:t groupByPathName (Unfold.take 10000000 archive)
packageStream & S.map (const 1) & S.sum
#+end_src

#+RESULTS:
: groupByPathName
:   :: S.IsStream t =>
:      Unfold IO a (Either Header ByteString)
:      -> t IO (ByteString, ByteString)
: Unfold.take 10000000 archive
:   :: Unfold IO Void (Either Header ByteString)
: groupByPathName (Unfold.take 10000000 archive)
:   :: S.IsStream t => t IO (ByteString, ByteString)
: 288831

** package names

*** weird name checks

#+begin_src haskell :results output :exports both
S.toList $ S.filter ((/= Just (Just FileTypeRegular)) . fmap fileType) $ S.take 10 $ fmap fst $ groupByHeader (Unfold.take 10000000 archive)

S.toList $ S.filter (\x -> fmap pathName x /= fmap pathNameUtf8 x) $ S.take 10 $ fmap fst $ groupByHeader (Unfold.take 10000000 archive)

S.toList $ S.filter (\x -> fmap pathName x == Nothing) $ S.take 10 $ fmap fst $ groupByHeader (Unfold.take 10000000 archive)
#+end_src

#+RESULTS:
: []
: > []
: > []

*** empty content

The first 10 package names

#+begin_src haskell :exports both
S.toList $ S.take 10 $ fmap fst packageStream
#+end_src

#+RESULTS:
| iconv/0.2/iconv.cabal | Crypto/3.0.3/Crypto.cabal | HDBC/1.0.1/HDBC.cabal | HDBC-odbc/1.0.1.0/HDBC-odbc.cabal | HDBC-postgresql/1.0.1.0/HDBC-postgresql.cabal | HDBC-sqlite3/1.0.1.0/HDBC-sqlite3.cabal | darcs-graph/0.1/darcs-graph.cabal | hask-home/2006.3.23/hask-home.cabal | hmp3/1.1/hmp3.cabal | lambdabot/4.0/lambdabot.cabal |

Some have no cabal file content, but these are =preferred-version= types.

#+begin_src haskell :exports both
S.length $ S.filter ((=="") . snd) $ packageStream
#+end_src

#+RESULTS:
: 42

*** types of packages

package path names are either preferred-versions, .cabal or package.json

#+begin_src haskell :exports both
S.length $ fmap fst $ S.filter (not . (\x -> B.isSuffixOf "preferred-versions" x || B.isSuffixOf ".cabal" x || B.isSuffixOf "package.json" x) . fst) $ packageStream
#+end_src

#+RESULTS:
: 0

Reifying this as NameType:

#+begin_src haskell :results output :exports both
:i NameType
S.fold count $ fmap (bimap toNameType (=="")) $ packageStream
#+end_src

#+RESULTS:
: type NameType :: *
: data NameType
:   = CabalName | PreferredVersions | PackageJson | BadlyNamed
:   	-- Defined at src/Research/Hackage.hs:192:1
: instance Show NameType -- Defined at src/Research/Hackage.hs:192:84
: instance Eq NameType -- Defined at src/Research/Hackage.hs:192:95
: instance Ord NameType -- Defined at src/Research/Hackage.hs:192:90
: fromList [((CabalName,False),159469),((PreferredVersions,False),2845),((PreferredVersions,True),42),((PackageJson,False),126475)]

**** preferred-versions

#+begin_src haskell :results output
S.toList $ S.take 10 $ S.filter (\(x,c) -> B.isSuffixOf "preferred-versions" x && c /= "") $ packages archive
#+end_src

#+RESULTS:
: [("ADPfusion/preferred-versions","ADPfusion <0.4.0.0 || >0.4.0.0"),("AesonBson/preferred-versions","AesonBson <0.2.0 || >0.2.0 && <0.2.1 || >0.2.1"),("BiobaseXNA/preferred-versions","BiobaseXNA <0.9.1.0 || >0.9.1.0"),("BufferedSocket/preferred-versions","BufferedSocket <0.1.0.0 || >0.1.0.0 && <0.1.1.0 || >0.1.1.0"),("FTGL/preferred-versions","FTGL <1.4 || >1.4"),("HSlippyMap/preferred-versions","HSlippyMap <0.1.0.0 || >0.1.0.0 && <1.0 || >1.0 && <1.2 || >1.2 && <1.4 || >1.4 && <1.6 || >1.6 && <1.8 || >1.8 && <2.0 || >2.0 && <2.1 || >2.1"),("HaTeX-qq/preferred-versions","HaTeX-qq <0.0.0.0 || >0.0.0.0 && <0.0.1.0 || >0.0.1.0"),("Hs2lib/preferred-versions","Hs2lib <0.5.7 || >0.5.7 && <0.5.8 || >0.5.8"),("Hungarian-Munkres/preferred-versions","Hungarian-Munkres <0.1.0 || >0.1.0 && <0.1.1 || >0.1.1 && <0.1.2 || >0.1.2"),("IPv6Addr/preferred-versions","IPv6Addr >=0.5")]

**** package-json

=package-json= content is a security/signing feature you can read about in [[https://github.com/haskell/hackage-security/blob/master/README.md][hackage-security]].

#+begin_src haskell :exports both
S.length $ S.filter ((\x -> B.isSuffixOf "package.json" x) . fst) $ packageStream
#+end_src

#+RESULTS:
: 126475


#+begin_src haskell
S.toList $ S.take 4 $ S.filter ((\x -> B.isSuffixOf "package.json" x) . fst) $ packageStream
#+end_src

#+RESULTS:
| Chart-cairo/1.0/package.json       | {"signatures":[],"signed":{"_type":"Targets","expires":null,"targets":{"<repo>/package/Chart-cairo-1.0.tar.gz":{"hashes":{"md5":"673158c2dedfb688291096fc818c5d5e","sha256":"a55c585310e65cf609c0de925d8c3616b1d8b74e803e149a184d979db086b87c"},"length":4510}},"version":0}}       |
| DistanceUnits/0.1.0.0/package.json | {"signatures":[],"signed":{"_type":"Targets","expires":null,"targets":{"<repo>/package/DistanceUnits-0.1.0.0.tar.gz":{"hashes":{"md5":"66fc96c89eaf434673f6cb8185f7b0d5","sha256":"6f82154cff8a245aeb2baee32276598bba95adca2220b36bafc37aa04d7b0f64"},"length":4473}},"version":0}} |
| Capabilities/0.1.0.0/package.json  | {"signatures":[],"signed":{"_type":"Targets","expires":null,"targets":{"<repo>/package/Capabilities-0.1.0.0.tar.gz":{"hashes":{"md5":"d6be3b7250cf729a281918ebb769fa33","sha256":"0434c5659c3f893942159bde4bd760089e81a3942f799010d04bd5bee0f6a559"},"length":6255}},"version":0}}  |
| Chart-diagrams/1.0/package.json    | {"signatures":[],"signed":{"_type":"Targets","expires":null,"targets":{"<repo>/package/Chart-diagrams-1.0.tar.gz":{"hashes":{"md5":"59bc95baee048eb74a1d104750c88e2d","sha256":"41beed8d265210f9ecd7488dfa83b76b203522d45425fd84b5943ebf84af17b5"},"length":1606758}},"version":0}} |

**** .cabal

#+begin_src haskell :exports both
S.length $ S.filter ((\x -> B.isSuffixOf ".cabal" x) . fst) $ packageStream
#+end_src

#+RESULTS:
: 159469

#+begin_src haskell
fmap fst <$> (S.toList $ S.take 10 $ S.filter ((\x -> B.isSuffixOf ".cabal" x) . fst) $ packageStream)
#+end_src

#+RESULTS:
| iconv/0.2/iconv.cabal | Crypto/3.0.3/Crypto.cabal | HDBC/1.0.1/HDBC.cabal | HDBC-odbc/1.0.1.0/HDBC-odbc.cabal | HDBC-postgresql/1.0.1.0/HDBC-postgresql.cabal | HDBC-sqlite3/1.0.1.0/HDBC-sqlite3.cabal | darcs-graph/0.1/darcs-graph.cabal | hask-home/2006.3.23/hask-home.cabal | hmp3/1.1/hmp3.cabal | lambdabot/4.0/lambdabot.cabal |

*** .cabal paths

So there is about 160k cabal files to R&D ...

malformed version number check

#+begin_src haskell :results output

mErrs <- S.fold (collect fst snd) $ S.filter (isLeft . snd) $ fmap (second (parseVersion . C.pack)) $ fmap (fromRight undefined) $ S.filter isRight $ fmap (Research.Hackage.parsePath . fst) $ S.filter ((==CabalName) . toNameType . fst) packageStream

length mErrs

#+end_src

#+RESULTS:
:
: > 0


Total number of names

#+begin_src haskell :exports both
t1 <- S.fold (collect fst snd) $ fmap (second (fromRight undefined)) $ S.filter (isRight . snd) $ fmap (second (parseVersion . C.pack)) $ fmap (fromRight undefined) $ S.filter isRight $ fmap (Research.Hackage.parsePath . fst) $ S.filter ((==CabalName) . toNameType . fst) packageStream

length t1
#+end_src

#+RESULTS:
: > 16511

Average number of versions:

#+begin_src haskell :results output :exports both
 fromIntegral (sum $ Map.elems $ length <$> t1) / fromIntegral (length t1)
#+end_src

#+RESULTS:
: 9.658348979468233


All of the latest cabal files have content:

#+begin_src haskell :exports both
latest = Map.map maximum t1
length $ Map.toList $ Map.filter (==[]) latest
#+end_src

#+RESULTS:
: 0

** latest versions

#+begin_src haskell :exports both
lcf <- latestCabalFiles
length $ Map.toList lcf
#+end_src

#+RESULTS:
: 16511

** field parsing errors

field errors

#+begin_src haskell :exports both
fmap (\x -> C.pack (fst x) <> "-" <> toVer (fst (snd x))) $ Map.toList $ Map.filter (isLeft . readFields . snd) lcf
#+end_src

#+RESULTS:
| DSTM-0.1.2 | control-monad-exception-mtl-0.10.3 | ds-kanren-0.2.0.1 | metric-0.2.0 | phasechange-0.1 | smartword-0.0.0.5 |

** busting up cabal files into fields

valid cabal files with ok parsing of all fields:

#+begin_src haskell :exports both
vlcs <- validLatestCabals
:t vlcs
length vlcs
#+end_src

#+RESULTS:
: 16505

*** field counts across all files

#+begin_src haskell
import Data.Ord
fmap (take 10 . List.sortOn (Down . snd) . Map.toList) $ S.fold count $ S.fromList $ fmap names $ mconcat $ fmap snd $ Map.toList $ fmap snd vlcs
#+end_src

#+RESULTS:
| license       | 16509 |
| name          | 16506 |
| version       | 16505 |
| maintainer    | 16431 |
| synopsis      | 16336 |
| cabal-version | 16240 |
| category      | 16133 |
| build-type    | 16097 |
| author        | 16023 |
| license-file  | 15883 |


*** authors

#+begin_src haskell
fmap (take 10 . List.sortOn (Down . snd) . Map.toList) $ S.fold count $ S.fromList $ mconcat $ fmap authors $ fmap snd $ Map.toList $ fmap snd vlcs
#+end_src

#+RESULTS:
| Brendan Hay                                        | 333 |
| Nikita Volkov <nikita.y.volkov@mail.ru>            | 145 |
| Tom Sydney Kerckhove                               | 108 |
| Henning Thielemann <haskell@henning-thielemann.de> | 103 |
| Andrew Martin                                      |  99 |
| Edward A. Kmett                                    |  98 |
| Michael Snoyman                                    |  88 |
| OleksandrZhabenko                                  |  82 |
| M Farkas-Dyck                                      |  78 |
| Vanessa McHale                                     |  78 |

** libraries

not libraries

#+begin_src haskell :exports both
Map.size $ Map.filter ((0==) . length) $ fmap (catMaybes . fmap (sec "library") . snd) vlcs
#+end_src

#+RESULTS:
: 1725

multiple libraries

#+begin_src haskell :exports both
Map.size $ Map.filter ((>1) . length) $ fmap (catMaybes . fmap (sec "library") . snd) vlcs
#+end_src

#+RESULTS:
: 66

Multiple libraries are usually "internal" libraries that can only be used inside the cabal file.

#+begin_src haskell :results output
take 10 $ Map.toList $ Map.filter (\x -> x/=[[]] && x/=[] && listToMaybe x /= Just []) $ fmap (fmap (fmap secName) . fmap fst . catMaybes . fmap (sec "library") . snd) vlcs
#+end_src

#+RESULTS:
: [("LiterateMarkdown",[[("name","converter")]]),("attoparsec",[[("name","attoparsec-internal")],[]]),("buffet",[[("name","buffet-internal")]]),("cabal-fmt",[[("name","cabal-fmt-internal")]]),("cuckoo",[[("name","random-internal")],[]]),("dhrun",[[("name","dhrun-lib")]]),("dns",[[("name","dns-internal")],[]]),("escoger",[[("name","escoger-lib")]]),("ghc-plugs-out",[[("name","no-op-plugin")],[("name","undefined-init-plugin")],[("name","undefined-solve-plugin")],[("name","undefined-stop-plugin")],[("name","call-count-plugin")]]),("haskell-ci",[[("name","haskell-ci-internal")]])]


common stanzas

#+begin_src haskell :exports both
length $ Map.toList $ Map.filter (/=[]) $ fmap (catMaybes . fmap (sec "common")) $ fmap snd vlcs
#+end_src

#+RESULTS:
: 568

valid cabal files that have a library section:

#+begin_src haskell :exports both
vlibs <- Map.delete "acme-everything" <$> validLatestLibs
Map.size vlibs
#+end_src

#+RESULTS:
: 14779

** dependencies

Total number of build dependencies in library stanzas and in common stanzas:

#+begin_src haskell :results output :exports both
sum $ fmap snd $ Map.toList $ fmap (sum . fmap length) $ fmap (fmap (fieldValues "build-depends")) $ Map.filter (/=[]) $ fmap (fmap snd . catMaybes . fmap (sec "library") . snd) vlibs

sum $ fmap snd $ Map.toList $ fmap (sum . fmap length) $ fmap (fmap (fieldValues "build-depends")) $ Map.filter (/=[]) $ fmap (fmap snd . catMaybes . fmap (sec "common") . snd) vlibs
#+end_src

#+RESULTS:
: 105233
: > 3440


no dependencies

#+begin_src haskell :exports both
Map.size $ Map.filter (==[]) $ fmap (rawBuildDeps . snd) $ Map.delete "acme-everything" vlcs
#+end_src

#+RESULTS:
: 1725

These are mostly parse errors from not properly parsing conditionals.

unique dependencies

#+begin_src haskell
Map.size $ fmap (fmap mconcat) $ Map.filter (/=[]) $ fmap (rawBuildDeps . snd) $ Map.delete "acme-everything" vlibs
#+end_src

#+RESULTS:
: 14779

raw build-deps example:

#+begin_src haskell :exports both
take 1 $ Map.toList $ fmap (fmap mconcat) $ Map.filter (/=[]) $ fmap (rawBuildDeps . snd) $ vlibs
#+end_src

#+RESULTS:
| 2captcha | (aeson >=1.5.6.0 && <1.6,base >=4.7 && <5,bytestring >=0.10.12.0 && <0.11,clock >=0.8.2 && <0.9,exceptions >=0.10.4 && <0.11,http-client >=0.6.4.1 && <0.7,lens >=4.19.2 && <4.20,lens-aeson >=1.1.1 && <1.2,parsec >=3.1.14.0 && <3.2,text >=1.2.4.1 && <1.3,wreq >=0.5.3.3 && <0.6 ) |

lex check:

#+begin_src haskell :exports both
S.fold count $ S.concatMap S.fromList $ fmap C.unpack $ S.concatMap S.fromList $ S.fromList $ fmap snd $ Map.toList $ fmap (fmap mconcat) $ Map.filter (/=[]) $ fmap (rawBuildDeps . snd) $ vlibs
#+end_src

#+RESULTS:
: fromList [('\t',42),(' ',572471),('&',86160),('(',486),(')',486),('*',5969),(',',92554),('-',32183),('.',140854),('0',77745),('1',63104),('2',32240),('3',20269),('4',29110),('5',22316),('6',9901),('7',9590),('8',6678),('9',6284),('<',45145),('=',78780),('>',65175),('A',259),('B',234),('C',1113),('D',474),('E',75),('F',143),('G',334),('H',809),('I',103),('J',112),('K',15),('L',502),('M',399),('N',79),('O',280),('P',422),('Q',602),('R',240),('S',544),('T',524),('U',200),('V',75),('W',73),('X',92),('Y',24),('Z',18),('^',2855),('a',73691),('b',29688),('c',35787),('d',20249),('e',109010),('f',12413),('g',16508),('h',16656),('i',52533),('j',527),('k',7435),('l',34131),('m',26121),('n',54342),('o',47497),('p',28317),('q',2380),('r',67213),('s',78990),('t',90097),('u',14024),('v',6600),('w',3782),('x',10090),('y',17960),('z',1406),('{',38),('|',1936),('}',38)]

** deps

parsing the dependencies for just the names:

#+begin_src haskell :results output :exports both
deps = fmap (fromRight undefined . parseDeps . mconcat . mconcat . rawBuildDeps . snd) vlibs
Map.size deps
sum $ Map.elems $ fmap length deps
#+end_src

#+RESULTS:
:
: 14779
: 106678

#+begin_src haskell :results output :exports both
take 3 $ Map.toList deps
#+end_src

#+RESULTS:
: [("2captcha",["aeson","base","bytestring","clock","exceptions","http-client","lens","lens-aeson","parsec","text","wreq"]),("3dmodels",["base","attoparsec","bytestring","linear","packer"]),("AAI",["base"])]

packages with the most dependencies:

#+begin_src haskell :exports both
take 10 $ List.sortOn (Down . snd) $ fmap (second length) $ Map.toList deps
#+end_src

#+RESULTS:
| yesod-platform  | 132 |
| planet-mitchell | 109 |
| raaz            | 104 |
| sockets         |  82 |
| ghcide          |  75 |
| pandoc          |  70 |
| sprinkles       |  67 |
| too-many-cells  |  67 |
| pantry-tmp      |  64 |
| purescript      |  62 |

dependees

#+begin_src haskell :exports both
fmap (take 20) $ fmap (List.sortOn (Down . snd)) $ fmap Map.toList $ S.fold count $ S.concatMap S.fromList $ S.fromList $ fmap snd $ Map.toList deps
#+end_src

#+RESULTS:
| base                 | 14221 |
| bytestring           |  5206 |
| text                 |  4743 |
| containers           |  4532 |
| mtl                  |  3378 |
| transformers         |  2991 |
| aeson                |  1927 |
| time                 |  1866 |
| vector               |  1740 |
| directory            |  1556 |
| filepath             |  1476 |
| template-haskell     |  1391 |
| unordered-containers |  1349 |
| deepseq              |  1193 |
| lens                 |  1150 |
| binary               |   910 |
| hashable             |   890 |
| array                |   860 |
| process              |   828 |
| exceptions           |   810 |


All the dependees found:

#+begin_src haskell :exports both
bdnames <- fmap (fmap fst) $ fmap Map.toList $ S.fold count $ S.concatMap S.fromList $ S.fromList $ fmap snd $ Map.toList deps

length bdnames
#+end_src

#+RESULTS:
: > 5628

*** dependency name errors

dependees not in the cabal index:

#+begin_src haskell :results output :exports both
length $ filter (not . (`elem` (Map.keys vlibs))) bdnames

take 10 $ filter (not . (`elem` (Map.keys vlibs))) bdnames

#+end_src

#+RESULTS:
: 233
: > ["Codec-Compression-LZF","Consumer","DOM","DebugTraceHelpers","FieldTrip","FindBin","HJavaScript","HTTP-Simple","Imlib","LRU"]

excluding these:

#+begin_src haskell :results output :exports both
depsExclude = filter (not . (`elem` (Map.keys vlibs))) bdnames
vdeps = fmap (filter (not . (`elem` depsExclude))) deps
Map.size vdeps
sum $ fmap snd $ Map.toList $ fmap length vdeps
#+end_src

#+RESULTS:
:
: > 14779
: 106238

*** ToDo potential error sources

- [X] error 1 - commas can be inside braces

- [ ] error 2 - plain old dodgy depends
  acme-everything, cabal, deprecated packages

- [ ] error 3 - multiple build-depends in one stanza

- [ ] error 4 - cpp & conditionals

- [ ] error 5 - packages not on Hackage

   cardano
   "This library requires quite a few exotic dependencies from the cardano realm which aren't necessarily on hackage nor stackage. The dependencies are listed in stack.yaml, make sure to also include those for importing cardano-transactions." ~ https://raw.githubusercontent.com/input-output-hk/cardano-haskell/d80bdbaaef560b8904a828197e3b94e667647749/snapshots/cardano-1.24.0.yaml

- [ ] error 6 - internal library (only available to the main cabal library stanza)
  yahoo-prices, vector-endian, symantic-parser

Empty lists are mostly due to bad conditional parsing

 #+begin_src haskell :exports both
 Map.size $ Map.filter null deps
 #+end_src

 #+RESULTS:
 : 243

** algebraic-graphs

An (algebraic) graph of dependencies:

#+begin_src haskell :results output
depG = stars (Map.toList vdeps)
#+end_src

#+RESULTS:

#+begin_src haskell :results output :export both
vertexCount depG
edgeCount depG
#+end_src

#+RESULTS:
: 14779
: 105693

** graphics

=text= package dependency example

#+begin_src haskell
 supers = upstreams "text" depG <> Set.singleton "text"
 superG = induce (`elem` (toList supers)) depG
 #+end_src

#+begin_src haskell :file other/textdeps.svg :results output graphics file :exports results
 baseGraph = defaultGraph & attL NodeType (ID "shape") .~ Just (ID "box") & gattL (ID "rankdir") .~ Just (IDQuoted "BT")
 g <- processGraph $ toDotGraphWith UnDirected baseGraph (fmap packUTF8 superG)
 writeChartSvg "other/textdeps.svg" (graphToChart g)
 #+end_src

 #+RESULTS:
 [[file:other/textdeps.svg]]


=mealy= package dependencies

#+begin_src haskell
 supers = upstreams "mealy" depG <> Set.singleton "mealy"
 superG = induce (`elem` (toList (Set.delete "base" supers))) depG
 #+end_src

#+begin_src haskell :file other/mealy.svg :results output graphics file :exports results
 g <- processGraph $ toDotGraphWith UnDirected baseGraph (fmap packUTF8 superG)
 writeChartSvg "other/mealy.svg" (graphToChart g)
 #+end_src

 #+RESULTS:
 [[file:other/mealy.svg]]

* reference

** packages

[[https://hackage.haskell.org/package/tar-0.5.1.1][tar: Reading, writing and manipulating ".tar" archive files.]]
[[https://hackage.haskell.org/package/tar-conduit][tar-conduit: Extract and create tar files using conduit for streaming]]
[[https://hackage.haskell.org/package/streamly-0.8.0/docs/Streamly-Prelude.html][Streamly.Prelude]]
[[https://hackage.haskell.org/package/flatparse-0.2.2.0/docs/FlatParse-Basic.html][FlatParse.Basic]]

** other hackage parsing examples

[[https://hackage.haskell.org/package/cabal-install-parsers-0.4.2][cabal-install-parsers]]
[[https://github.com/J-mie6/ParsleyHaskell][ParsleyHaskell]]
[[https://hackage.haskell.org/package/Cabal-3.6.1.0/docs/Distribution-Parsec.html#t:ParsecParser][Distribution.Parsec]]
